
services:
  pump_simulator:
    build: .
    container_name: fleet_simulator
    restart: unless-stopped
    env_file: .env
    networks:
      - pump_network
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

networks:
  pump_network:
    external: true